logs:
    - name: root
      level: info
      appenders:
          - type: FileLogAppender
            file: /home/wonderful/myserver/log/root.txt
          - type: StdoutLogAppender
    - name: system
      level: info
      appenders:
          - type: FileLogAppender
            file: /home/wonderful/myserver/log/system.txt
          - type: StdoutLogAppender